name: Docker Build and Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (for building multi-platform images if necessary)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Get the version tag (if exists) or fall back to the short commit SHA
      - name: Determine Docker Image Tag
        id: vars
        run: |
          # Get the latest tag or fallback to short SHA if not on a tag
          if [ "$(git describe --tags --exact-match 2>/dev/null)" ]; then
            echo "GIT_TAG=$(git describe --tags --exact-match)" >> $GITHUB_ENV
          else
            echo "GIT_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            diabl0/unmanicarr:latest
            diabl0/unmanicarr:${{ env.GIT_TAG }}
